const Invite=require('../models/Invite');const Ad=require('../models/Ad');const Notification=require('../models/Notification');const Activity=require('../models/Activity');const User=require('../models/User');
exports.sendInvite=async(req,res)=>{try{const{email,receiverId:requestedReceiverId,adId}=req.body;if(!email&&!requestedReceiverId)return res.status(400).json({success:false,message:'Please provide a receiver'});const receiver=requestedReceiverId?await User.findById(requestedReceiverId):await User.findOne({email});if(!receiver)return res.status(404).json({success:false,message:'User not found'});if(String(receiver._id)===String(req.user.id))return res.status(400).json({success:false,message:'Cannot invite yourself'});const existing=await Invite.findOne({senderId:req.user.id,receiverId:receiver._id,adId:adId||undefined,status:{$in:['pending','accepted']}});if(existing)return res.status(400).json({success:false,message:'Invite already sent to this user'});let snapshot={};if(adId){const post=await Ad.findById(adId).select('user category subCategory location subLocation headline');if(!post)return res.status(404).json({success:false,message:'Post not found'});if(String(post.user)!==String(receiver._id))return res.status(400).json({success:false,message:'Recipient must own the selected post'});snapshot={category:post.category,subCategory:post.subCategory||'',location:post.location,subLocation:post.subLocation||''};}const invite=await Invite.create({senderId:req.user.id,receiverId:receiver._id,adId:adId||undefined,status:'pending',...snapshot});const sender=await User.findById(req.user.id);await Notification.create({userId:receiver._id,title:'New Invite',message:(sender?.name||'A user')+' has sent you an invite.',type:'invite',referenceId:invite._id,referenceType:'invite',isRead:false});req.app.get('socketio')?.to(String(receiver._id)).emit('notification received');await Activity.create({userId:req.user.id,actionText:'You sent an invite to '+(receiver.name||'a user')});res.status(201).json({success:true,data:invite});}catch(e){res.status(500).json({success:false,message:'Server Error'});}};
exports.updateInvite=async(req,res)=>{try{const{status}=req.body;if(!['accepted','rejected','cancelled'].includes(status))return res.status(400).json({success:false,message:'Invalid invite status'});
const ownershipFilter = status === 'cancelled'
    ? { _id:req.params.id, senderId:req.user.id, status:'pending' }
    : { _id:req.params.id, receiverId:req.user.id, status:'pending' };
const invite=await Invite.findOneAndUpdate(ownershipFilter,{status},{new:true}).populate('senderId','name email mobile').populate('receiverId','name email mobile').populate('adId','headline postRole category location');if(!invite)return res.status(404).json({success:false,message:'Invite not found'});await Notification.create({userId:invite.senderId._id,title:status==='accepted'?'Invite accepted':'Invite declined',message:status==='cancelled'
    ? 'You cancelled your invite to '+(invite.receiverId?.name||'the post owner')+'.'
    : (invite.receiverId?.name||'The post owner')+' has '+status+' your invite.',type:'invite',referenceId:invite._id,referenceType:'invite',isRead:false});req.app.get('socketio')?.to(String(invite.senderId._id)).emit('notification received');res.json({success:true,data:invite});}catch(e){res.status(500).json({success:false,message:'Server Error'});}};
exports.getInvites=async(req,res)=>{try{
const adFilter = req.query.adId ? { adId:req.query.adId } : {};
const[received,sent]=await Promise.all([Invite.find({receiverId:req.user.id,...adFilter}).populate('senderId','name email mobile').populate('adId','headline postRole category location').sort({createdAt:-1}).lean(),Invite.find({senderId:req.user.id,...adFilter}).populate('receiverId','name email mobile').populate('adId','headline postRole category location').sort({createdAt:-1}).lean()]);const data=[...received,...sent].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));res.json({success:true,count:data.length,data,received,sent});}catch(e){res.status(500).json({success:false,message:'Server Error'});}};