const Proposal=require('../models/Proposal');const Ad=require('../models/Ad');const Notification=require('../models/Notification');const User=require('../models/User');
exports.createProposal=async(req,res)=>{try{const{adId,message,proposalType='investment'}=req.body;if(!adId||typeof message!=='string'||!message.trim())return res.status(400).json({success:false,message:'A post and proposal message are required.'});if(message.trim().length>3000)return res.status(400).json({success:false,message:'Proposal is too long.'});const ad=await Ad.findById(adId).select('user headline status postRole');if(!ad?.user)return res.status(404).json({success:false,message:'Post owner not found.'});if(ad.status!=='active')return res.status(409).json({success:false,message:'Proposals require an active post.'});if(String(ad.user)===String(req.user.id))return res.status(400).json({success:false,message:'You cannot send a proposal to your own post.'});const existing=await Proposal.findOne({senderId:req.user.id,receiverId:ad.user,adId,status:'pending'});if(existing)return res.status(409).json({success:false,message:'You already have a pending proposal.'});const proposal=await Proposal.create({senderId:req.user.id,receiverId:ad.user,adId,message:message.trim(),proposalType});const sender=await User.findById(req.user.id).select('name storeName');await Notification.create({userId:ad.user,title:'New investment proposal',message:(sender?.storeName||sender?.name||'A member')+' sent a proposal for “'+ad.headline+'”.',type:'proposal',referenceId:proposal._id,referenceType:'proposal'});req.app.get('socketio')?.to(String(ad.user)).emit('notification received');res.status(201).json({success:true,data:proposal});}catch(e){res.status(500).json({success:false,message:'Unable to send proposal.'});}};
exports.getProposals=async(req,res)=>{try{const[received,sent]=await Promise.all([Proposal.find({receiverId:req.user.id}).populate('senderId','name storeName mobile mVerified').populate('adId','headline description postRole category subCategory location subLocation businessStatus price priceType minInvestment maxInvestment expectedReturn investmentReturnType investmentReturn priceBoxValues priceBoxFields features').sort({createdAt:-1}).lean(),Proposal.find({senderId:req.user.id}).populate('receiverId','name storeName mobile mVerified').populate('adId','headline description postRole category subCategory location subLocation businessStatus price priceType minInvestment maxInvestment expectedReturn investmentReturnType investmentReturn priceBoxValues priceBoxFields features').sort({createdAt:-1}).lean()]);const data=[...received,...sent].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));res.json({success:true,data,received,sent});}catch(e){res.status(500).json({success:false,message:'Unable to load proposals.'});}};
exports.updateProposal=async(req,res)=>{try{const{status}=req.body;if(!['accepted','rejected','cancelled'].includes(status))return res.status(400).json({success:false,message:'Invalid proposal status.'});
const ownershipFilter = status === 'cancelled'
    ? { _id:req.params.id, senderId:req.user.id, status:'pending' }
    : { _id:req.params.id, receiverId:req.user.id, status:'pending' };
const proposal=await Proposal.findOneAndUpdate(ownershipFilter,{status},{new:true}).populate('senderId','name mobile').populate('adId','headline description postRole category subCategory location subLocation businessStatus price priceType minInvestment maxInvestment expectedReturn investmentReturnType investmentReturn priceBoxValues priceBoxFields features');if(!proposal)return res.status(404).json({success:false,message:'Proposal not found.'});await Notification.create({userId:proposal.senderId._id,title:'Proposal '+status,message:status==='cancelled'
    ? 'You cancelled your proposal for “'+(proposal.adId?.headline||'a post')+'”.'
    : 'Your proposal for “'+(proposal.adId?.headline||'a post')+'” was '+status+'.',type:'proposal',referenceId:proposal._id,referenceType:'proposal'});req.app.get('socketio')?.to(String(proposal.senderId._id)).emit('notification received');res.json({success:true,data:proposal});}catch(e){res.status(500).json({success:false,message:'Unable to update proposal.'});}};